// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: keeper.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTextRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetTextRequest) Reset() {
	*x = GetTextRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keeper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTextRequest) ProtoMessage() {}

func (x *GetTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTextRequest.ProtoReflect.Descriptor instead.
func (*GetTextRequest) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{0}
}

func (x *GetTextRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetTextResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetTextResponse) Reset() {
	*x = GetTextResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keeper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTextResponse) ProtoMessage() {}

func (x *GetTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTextResponse.ProtoReflect.Descriptor instead.
func (*GetTextResponse) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{1}
}

func (x *GetTextResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GetTextResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SaveTextRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *SaveTextRequest) Reset() {
	*x = SaveTextRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keeper_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveTextRequest) ProtoMessage() {}

func (x *SaveTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveTextRequest.ProtoReflect.Descriptor instead.
func (*SaveTextRequest) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{2}
}

func (x *SaveTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SaveTextRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SaveTextResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *SaveTextResponse) Reset() {
	*x = SaveTextResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keeper_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveTextResponse) ProtoMessage() {}

func (x *SaveTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveTextResponse.ProtoReflect.Descriptor instead.
func (*SaveTextResponse) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{3}
}

func (x *SaveTextResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetBytesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetBytesRequest) Reset() {
	*x = GetBytesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keeper_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBytesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBytesRequest) ProtoMessage() {}

func (x *GetBytesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBytesRequest.ProtoReflect.Descriptor instead.
func (*GetBytesRequest) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{4}
}

func (x *GetBytesRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetBytesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*GetBytesResponse_Filename
	//	*GetBytesResponse_Chunk
	//	*GetBytesResponse_HashSum
	Data isGetBytesResponse_Data `protobuf_oneof:"data"`
}

func (x *GetBytesResponse) Reset() {
	*x = GetBytesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keeper_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBytesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBytesResponse) ProtoMessage() {}

func (x *GetBytesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBytesResponse.ProtoReflect.Descriptor instead.
func (*GetBytesResponse) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{5}
}

func (m *GetBytesResponse) GetData() isGetBytesResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *GetBytesResponse) GetFilename() string {
	if x, ok := x.GetData().(*GetBytesResponse_Filename); ok {
		return x.Filename
	}
	return ""
}

func (x *GetBytesResponse) GetChunk() []byte {
	if x, ok := x.GetData().(*GetBytesResponse_Chunk); ok {
		return x.Chunk
	}
	return nil
}

func (x *GetBytesResponse) GetHashSum() string {
	if x, ok := x.GetData().(*GetBytesResponse_HashSum); ok {
		return x.HashSum
	}
	return ""
}

type isGetBytesResponse_Data interface {
	isGetBytesResponse_Data()
}

type GetBytesResponse_Filename struct {
	Filename string `protobuf:"bytes,1,opt,name=filename,proto3,oneof"`
}

type GetBytesResponse_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

type GetBytesResponse_HashSum struct {
	HashSum string `protobuf:"bytes,3,opt,name=hashSum,proto3,oneof"`
}

func (*GetBytesResponse_Filename) isGetBytesResponse_Data() {}

func (*GetBytesResponse_Chunk) isGetBytesResponse_Data() {}

func (*GetBytesResponse_HashSum) isGetBytesResponse_Data() {}

type SaveBytesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*SaveBytesRequest_Filename
	//	*SaveBytesRequest_Chunk
	//	*SaveBytesRequest_HashSum
	Data isSaveBytesRequest_Data `protobuf_oneof:"data"`
}

func (x *SaveBytesRequest) Reset() {
	*x = SaveBytesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keeper_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveBytesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveBytesRequest) ProtoMessage() {}

func (x *SaveBytesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveBytesRequest.ProtoReflect.Descriptor instead.
func (*SaveBytesRequest) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{6}
}

func (m *SaveBytesRequest) GetData() isSaveBytesRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *SaveBytesRequest) GetFilename() string {
	if x, ok := x.GetData().(*SaveBytesRequest_Filename); ok {
		return x.Filename
	}
	return ""
}

func (x *SaveBytesRequest) GetChunk() []byte {
	if x, ok := x.GetData().(*SaveBytesRequest_Chunk); ok {
		return x.Chunk
	}
	return nil
}

func (x *SaveBytesRequest) GetHashSum() string {
	if x, ok := x.GetData().(*SaveBytesRequest_HashSum); ok {
		return x.HashSum
	}
	return ""
}

type isSaveBytesRequest_Data interface {
	isSaveBytesRequest_Data()
}

type SaveBytesRequest_Filename struct {
	Filename string `protobuf:"bytes,1,opt,name=filename,proto3,oneof"`
}

type SaveBytesRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

type SaveBytesRequest_HashSum struct {
	HashSum string `protobuf:"bytes,3,opt,name=hashSum,proto3,oneof"`
}

func (*SaveBytesRequest_Filename) isSaveBytesRequest_Data() {}

func (*SaveBytesRequest_Chunk) isSaveBytesRequest_Data() {}

func (*SaveBytesRequest_HashSum) isSaveBytesRequest_Data() {}

type SaveBytesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *SaveBytesResponse) Reset() {
	*x = SaveBytesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keeper_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveBytesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveBytesResponse) ProtoMessage() {}

func (x *SaveBytesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveBytesResponse.ProtoReflect.Descriptor instead.
func (*SaveBytesResponse) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{7}
}

func (x *SaveBytesResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

var File_keeper_proto protoreflect.FileDescriptor

var file_keeper_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x39, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x65, 0x78, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x39, 0x0a, 0x0f, 0x53, 0x61, 0x76, 0x65, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x22, 0x0a, 0x10, 0x53,
	0x61, 0x76, 0x65, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22,
	0x21, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x79, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x49, 0x44, 0x22, 0x6c, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x42, 0x79, 0x74, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x1a, 0x0a, 0x07,
	0x68, 0x61, 0x73, 0x68, 0x53, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x07, 0x68, 0x61, 0x73, 0x68, 0x53, 0x75, 0x6d, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x6c, 0x0a, 0x10, 0x53, 0x61, 0x76, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x48, 0x00, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x1a, 0x0a, 0x07, 0x68, 0x61,
	0x73, 0x68, 0x53, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x68,
	0x61, 0x73, 0x68, 0x53, 0x75, 0x6d, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x23,
	0x0a, 0x11, 0x53, 0x61, 0x76, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x49, 0x44, 0x32, 0x8f, 0x02, 0x0a, 0x0d, 0x4b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x54, 0x65, 0x78, 0x74,
	0x12, 0x16, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x78,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3d, 0x0a, 0x08, 0x53, 0x61, 0x76, 0x65, 0x54, 0x65, 0x78, 0x74, 0x12, 0x17, 0x2e,
	0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x54, 0x65, 0x78, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e,
	0x53, 0x61, 0x76, 0x65, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3f, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x17, 0x2e, 0x6b,
	0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x74, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x47,
	0x65, 0x74, 0x42, 0x79, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30,
	0x01, 0x12, 0x42, 0x0a, 0x09, 0x53, 0x61, 0x76, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x18,
	0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x28, 0x01, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_keeper_proto_rawDescOnce sync.Once
	file_keeper_proto_rawDescData = file_keeper_proto_rawDesc
)

func file_keeper_proto_rawDescGZIP() []byte {
	file_keeper_proto_rawDescOnce.Do(func() {
		file_keeper_proto_rawDescData = protoimpl.X.CompressGZIP(file_keeper_proto_rawDescData)
	})
	return file_keeper_proto_rawDescData
}

var file_keeper_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_keeper_proto_goTypes = []any{
	(*GetTextRequest)(nil),    // 0: keeper.GetTextRequest
	(*GetTextResponse)(nil),   // 1: keeper.GetTextResponse
	(*SaveTextRequest)(nil),   // 2: keeper.SaveTextRequest
	(*SaveTextResponse)(nil),  // 3: keeper.SaveTextResponse
	(*GetBytesRequest)(nil),   // 4: keeper.GetBytesRequest
	(*GetBytesResponse)(nil),  // 5: keeper.GetBytesResponse
	(*SaveBytesRequest)(nil),  // 6: keeper.SaveBytesRequest
	(*SaveBytesResponse)(nil), // 7: keeper.SaveBytesResponse
}
var file_keeper_proto_depIdxs = []int32{
	0, // 0: keeper.KeeperService.GetText:input_type -> keeper.GetTextRequest
	2, // 1: keeper.KeeperService.SaveText:input_type -> keeper.SaveTextRequest
	4, // 2: keeper.KeeperService.GetBytes:input_type -> keeper.GetBytesRequest
	6, // 3: keeper.KeeperService.SaveBytes:input_type -> keeper.SaveBytesRequest
	1, // 4: keeper.KeeperService.GetText:output_type -> keeper.GetTextResponse
	3, // 5: keeper.KeeperService.SaveText:output_type -> keeper.SaveTextResponse
	5, // 6: keeper.KeeperService.GetBytes:output_type -> keeper.GetBytesResponse
	7, // 7: keeper.KeeperService.SaveBytes:output_type -> keeper.SaveBytesResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_keeper_proto_init() }
func file_keeper_proto_init() {
	if File_keeper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_keeper_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetTextRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keeper_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetTextResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keeper_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SaveTextRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keeper_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SaveTextResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keeper_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetBytesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keeper_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetBytesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keeper_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*SaveBytesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keeper_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*SaveBytesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_keeper_proto_msgTypes[5].OneofWrappers = []any{
		(*GetBytesResponse_Filename)(nil),
		(*GetBytesResponse_Chunk)(nil),
		(*GetBytesResponse_HashSum)(nil),
	}
	file_keeper_proto_msgTypes[6].OneofWrappers = []any{
		(*SaveBytesRequest_Filename)(nil),
		(*SaveBytesRequest_Chunk)(nil),
		(*SaveBytesRequest_HashSum)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_keeper_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_keeper_proto_goTypes,
		DependencyIndexes: file_keeper_proto_depIdxs,
		MessageInfos:      file_keeper_proto_msgTypes,
	}.Build()
	File_keeper_proto = out.File
	file_keeper_proto_rawDesc = nil
	file_keeper_proto_goTypes = nil
	file_keeper_proto_depIdxs = nil
}
